### ISSUE TITLE
Quality

### ISSUE THREAD

**Issue by fenix23707** [tinmn9088/manga-download#4]
You should make it better!!!!!!!!!!!!!!!!!
You should make it better!!!!!!!!!!!!!!!!!
You should make it better!!!!!!!!!!!!!!!!!
You should make it better!!!!!!!!!!!!!!!!!
You should make it better!!!!!!!!!!!!!!!!!
You should make it better!!!!!!!!!!!!!!!!!
You should make it better!!!!!!!!!!!!!!!!!
You should make it better!!!!!!!!!!!!!!!!!
You should make it better!!!!!!!!!!!!!!!!!
You should make it better!!!!!!!!!!!!!!!!!
You should make it better!!!!!!!!!!!!!!!!!
You should make it better!!!!!!!!!!!!!!!!!
You should make it better!!!!!!!!!!!!!!!!!
You should make it better!!!!!!!!!!!!!!!!!
You should make it better!!!!!!!!!!!!!!!!!
You should make it better!!!!!!!!!!!!!!!!!
You should make it better!!!!!!!!!!!!!!!!!
You should make it better!!!!!!!!!!!!!!!!!
You should make it better!!!!!!!!!!!!!!!!!
You should make it better!!!!!!!!!!!!!!!!!
You should make it better!!!!!!!!!!!!!!!!!
You should make it better!!!!!!!!!!!!!!!!!
You should make it better!!!!!!!!!!!!!!!!!
You should make it better!!!!!!!!!!!!!!!!!
You should make it better!!!!!!!!!!!!!!!!!
You should make it better!!!!!!!!!!!!!!!!!
You should make it better!!!!!!!!!!!!!!!!!
You should make it better!!!!!!!!!!!!!!!!!
You should make it better!!!!!!!!!!!!!!!!!
You should make it better!!!!!!!!!!!!!!!!!
You should make it better!!!!!!!!!!!!!!!!!
You should make it better!!!!!!!!!!!!!!!!!
You should make it better!!!!!!!!!!!!!!!!!
You should make it better!!!!!!!!!!!!!!!!!
You should make it better!!!!!!!!!!!!!!!!!
You should make it better!!!!!!!!!!!!!!!!!
You should make it better!!!!!!!!!!!!!!!!!
You should make it better!!!!!!!!!!!!!!!!!
You should make it better!!!!!!!!!!!!!!!!!
You should make it better!!!!!!!!!!!!!!!!!
You should make it better!!!!!!!!!!!!!!!!!
You should make it better!!!!!!!!!!!!!!!!!
You should make it better!!!!!!!!!!!!!!!!!
You should make it better!!!!!!!!!!!!!!!!!
You should make it better!!!!!!!!!!!!!!!!!
You should make it better!!!!!!!!!!!!!!!!!
You should make it better!!!!!!!!!!!!!!!!!
You should make it better!!!!!!!!!!!!!!!!!
You should make it better!!!!!!!!!!!!!!!!!
You should make it better!!!!!!!!!!!!!!!!!
You should make it better!!!!!!!!!!!!!!!!!
You should make it better!!!!!!!!!!!!!!!!!
You should make it better!!!!!!!!!!!!!!!!!
You should make it better!!!!!!!!!!!!!!!!!
You should make it better!!!!!!!!!!!!!!!!!
You should make it better!!!!!!!!!!!!!!!!!
You should make it better!!!!!!!!!!!!!!!!!
You should make it better!!!!!!!!!!!!!!!!!
You should make it better!!!!!!!!!!!!!!!!!
You should make it better!!!!!!!!!!!!!!!!!
You should make it better!!!!!!!!!!!!!!!!!
You should make it better!!!!!!!!!!!!!!!!!
You should make it better!!!!!!!!!!!!!!!!!
You should make it better!!!!!!!!!!!!!!!!!
You should make it better!!!!!!!!!!!!!!!!!
You should make it better!!!!!!!!!!!!!!!!!
You should make it better!!!!!!!!!!!!!!!!!
You should make it better!!!!!!!!!!!!!!!!!
You should make it better!!!!!!!!!!!!!!!!!
You should make it better!!!!!!!!!!!!!!!!!
You should make it better!!!!!!!!!!!!!!!!!
You should make it better!!!!!!!!!!!!!!!!!
You should make it better!!!!!!!!!!!!!!!!!
You should make it better!!!!!!!!!!!!!!!!!
You should make it better!!!!!!!!!!!!!!!!!
You should make it better!!!!!!!!!!!!!!!!!
You should make it better!!!!!!!!!!!!!!!!!
You should make it better!!!!!!!!!!!!!!!!!
You should make it better!!!!!!!!!!!!!!!!!
You should make it better!!!!!!!!!!!!!!!!!
You should make it better!!!!!!!!!!!!!!!!!
You should make it better!!!!!!!!!!!!!!!!!
You should make it better!!!!!!!!!!!!!!!!!
You should make it better!!!!!!!!!!!!!!!!!

**Comment by tinmn9088** [comment]
Good evening, fenix23707. Thanks for your review and sorry for the inconvenience. Could you please provide the issue details.

**Comment by fenix23707** [comment]
> Good evening, fenix23707. Thanks for your review and sorry for the inconvenience. Could you please provide the issue details.
Hi tinmn9088, I have reviewed your application and believe you can do it better. Just try it and I'm sure you will succeed!!!

**Comment by fenix23707** [comment]
bonne chance @tinmn9088

**Comment by fenix23707** [comment]
![better](https://user-images.githubusercontent.com/81484108/190332399-3d9eb82f-aaed-4d16-9cbf-6e71074d7658.jpg)
